-- Step 1: Identify the Course Schedule
SELECT SCHEDULE_ID
FROM ENROLLMENT
WHERE STUDENT_ID = 401 AND COURSE_NUM = 101; -- Example student_id and course_num

-- Step 2: Retrieve Grade Distribution
SELECT *
FROM GRADE_DISTRIBUTION
WHERE COURSE_NUM = 101 AND SCHEDULE_ID = (SELECT SCHEDULE_ID FROM ENROLLMENT WHERE STUDENT_ID = 401 AND COURSE_NUM = 101);

-- Step 3: Calculate Grade Components
-- Here, we calculate the grades for assignments, projects, tests, and participation based on their respective IDs and the weights provided in the grade distribution.
-- Additionally, we consider the number of assignments for each category.

-- Example calculation for assignment grade:
SELECT 
    SUM((ASSIGNMENT.GRADE / GRADE_DISTRIBUTION.NUM_HW) * (GRADE_DISTRIBUTION.HW_PERCENTAGE / 100)) AS assignment_grade,
    SUM((PROJECT.GRADE / GRADE_DISTRIBUTION.NUM_PROJ) * (GRADE_DISTRIBUTION.PROJECT_PERCENTAGE / 100)) AS project_grade,
    SUM((TEST.GRADE / GRADE_DISTRIBUTION.NUM_TESTS) * (GRADE_DISTRIBUTION.TESTS_PERCENTAGE / 100)) AS test_grade,
    SUM((PARTICIPATION.GRADE / COUNT(PARTICIPATION.PARTICIPATION_ID)) * (GRADE_DISTRIBUTION.PARTICIPATION_PERCENTAGE / 100)) AS participation_grade
FROM 
    ASSIGNMENT
INNER JOIN 
    GRADE_DISTRIBUTION ON ASSIGNMENT.COURSE_NUM = GRADE_DISTRIBUTION.COURSE_NUM
INNER JOIN 
    PROJECT ON ASSIGNMENT.COURSE_NUM = PROJECT.COURSE_NUM
INNER JOIN 
    TEST ON ASSIGNMENT.COURSE_NUM = TEST.COURSE_NUM
INNER JOIN 
    PARTICIPATION ON ASSIGNMENT.COURSE_NUM = PARTICIPATION.COURSE_NUM
WHERE 
    ASSIGNMENT.COURSE_NUM = 101;

-- Step 4: Compute Final Grade
-- Combine the weighted grades calculated in Step 3 to compute the final grade for the student.

-- Example combining grades:
SELECT
    (assignment_grade + project_grade + test_grade + participation_grade) AS final_grade
FROM (
    SELECT 
        SUM((ASSIGNMENT.GRADE / GRADE_DISTRIBUTION.NUM_HW) * (GRADE_DISTRIBUTION.HW_PERCENTAGE / 100)) AS assignment_grade,
        SUM((PROJECT.GRADE / GRADE_DISTRIBUTION.NUM_PROJ) * (GRADE_DISTRIBUTION.PROJECT_PERCENTAGE / 100)) AS project_grade,
        SUM((TEST.GRADE / GRADE_DISTRIBUTION.NUM_TESTS) * (GRADE_DISTRIBUTION.TESTS_PERCENTAGE / 100)) AS test_grade,
        SUM((PARTICIPATION.GRADE / COUNT(PARTICIPATION.PARTICIPATION_ID)) * (GRADE_DISTRIBUTION.PARTICIPATION_PERCENTAGE / 100)) AS participation_grade
    FROM 
        ASSIGNMENT
    INNER JOIN 
        GRADE_DISTRIBUTION ON ASSIGNMENT.COURSE_NUM = GRADE_DISTRIBUTION.COURSE_NUM
    INNER JOIN 
        PROJECT ON ASSIGNMENT.COURSE_NUM = PROJECT.COURSE_NUM
    INNER JOIN 
        TEST ON ASSIGNMENT.COURSE_NUM = TEST.COURSE_NUM
    INNER JOIN 
        PARTICIPATION ON ASSIGNMENT.COURSE_NUM = PARTICIPATION.COURSE_NUM
    WHERE 
        ASSIGNMENT.COURSE_NUM = 101
) AS combined_grades;
