UPDATE ASSIGNMENT
SET GRADE = CASE 
                WHEN COALESCE(GRADE, 0) + 2 > 100 THEN 100 
                ELSE COALESCE(GRADE, 0) + 2 
            END
FROM GRADE, ENROLLMENT, COURSE_SCHEDULE, COURSE
WHERE 
    GRADE.GRADE_ID = ASSIGNMENT.GRADE_ID AND
    GRADE.GRADE_ID = ENROLLMENT.GRADE_ID AND
    ENROLLMENT.COURSE_NUM = COURSE_SCHEDULE.COURSE_NUM AND
    ENROLLMENT.SCHEDULE_ID = COURSE_SCHEDULE.SCHEDULE_ID AND
    COURSE_SCHEDULE.COURSE_NUM = COURSE.COURSE_NUM AND
    ASSIGNMENT.ASSIGNMENT_NAME = 'List Basics' AND
    COURSE.COURSE_NAME = 'Introduction to Computer Science' AND
    COURSE_SCHEDULE.SEMESTER = 'Fall 2024';
