-- Create table COURSE
CREATE TABLE COURSE (
    COURSE_NUM INT PRIMARY KEY,
    COURSE_NAME VARCHAR(100)
);

-- Create table PROFESSOR
CREATE TABLE PROFESSOR (
    PROFESSOR_ID INT PRIMARY KEY,
    F_NAME VARCHAR(50),
    L_NAME VARCHAR(50),
    DEPARTMENT_NAME VARCHAR(255)
);

-- Create table COURSE_SCHEDULE
CREATE TABLE COURSE_SCHEDULE (
    SCHEDULE_ID INT,
    COURSE_NUM INT,
    SEMESTER VARCHAR(50),
    PROFESSOR_ID INT,
    PRIMARY KEY (SCHEDULE_ID, COURSE_NUM),
    FOREIGN KEY (COURSE_NUM) REFERENCES COURSE(COURSE_NUM),
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(PROFESSOR_ID)
);

-- Create table STUDENT
CREATE TABLE STUDENT (
    STUDENT_ID INT PRIMARY KEY,
    F_NAME VARCHAR(50),
    L_NAME VARCHAR(50)
);

-- Create table ENROLLMENT
CREATE TABLE ENROLLMENT (
    ENROLLMENT_ID INT,
    STUDENT_ID INT,
    SCHEDULE_ID INT,
    COURSE_NUM INT,
    PRIMARY KEY (ENROLLMENT_ID, STUDENT_ID, SCHEDULE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (COURSE_NUM, SCHEDULE_ID) REFERENCES COURSE_SCHEDULE(COURSE_NUM, SCHEDULE_ID)
);

-- Create table DISTRIBUTION
CREATE TABLE GRADE_DISTRIBUTION (
    DISTRIBUTION_ID INT,
    COURSE_NUM INT,
    SCHEDULE_ID INT,
    NUM_HW INT,
    NUM_PROJ INT,
    PARTICIPATION_PERCENTAGE INT,
    HW_PERCENTAGE INT,
    NUM_TESTS INT,
    TESTS_PERCENTAGE INT,
    PRIMARY KEY (DISTRIBUTION_ID, COURSE_NUM, SCHEDULE_ID),
    FOREIGN KEY (COURSE_NUM, SCHEDULE_ID) REFERENCES COURSE_SCHEDULE(COURSE_NUM, SCHEDULE_ID)
);

-- Create table ASSIGNMENT
CREATE TABLE ASSIGNMENT (
    ASSIGNMENT_ID INT PRIMARY KEY,
    ASSIGNMENT_NUM INT,
    GRADE INT
);

-- Create table PROJECT
CREATE TABLE PROJECT (
    PROJECT_ID INT PRIMARY KEY,
    PROJECT_NUM INT,
    GRADE INT
);

-- Create table TEST
CREATE TABLE TEST (
    TEST_ID INT PRIMARY KEY,
    TEST_NUM INT,
    GRADE INT
);

-- Create table PARTICIPATION
CREATE TABLE PARTICIPATION (
    PARTICIPATION_ID INT PRIMARY KEY,
    GRADE INT
);

-- Create table GRADE
CREATE TABLE GRADE (
    GRADE_ID INT PRIMARY KEY,
    ASSIGNMENT_ID INT,
    PROJECT_ID INT,
    TEST_ID INT,
    PARTICIPATION_ID INT,
    FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENT(ASSIGNMENT_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (TEST_ID) REFERENCES TEST(TEST_ID),
    FOREIGN KEY (PARTICIPATION_ID) REFERENCES PARTICIPATION(PARTICIPATION_ID)
);

