SELECT
STUDENT.F_NAME As First_Name, 
STUDENT.L_NAME As Last_Name
FROM STUDENT
INNER JOIN ENROLLMENT ON ENROLLMENT.STUDENT_ID = STUDENT.STUDENT_ID
WHERE ENROLLMENT.COURSE_NUM = 102
AND ENROLLMENT.SCHEDULE_ID IN (SELECT SCHEDULE_ID
                         FROM COURSE_SCHEDULE
                         WHERE SEMESTER = 'Fall 2024');