UPDATE ASSIGNMENT
SET GRADE = CASE
                WHEN ASSIGNMENT.GRADE IS NOT NULL AND STUDENT.L_NAME LIKE '%Q' THEN
                    CASE
                        WHEN ASSIGNMENT.GRADE + 2 > 100 THEN 100
                        ELSE ASSIGNMENT.GRADE + 2
                    END
                ELSE ASSIGNMENT.GRADE
            END
FROM ENROLLMENT
JOIN STUDENT ON ENROLLMENT.STUDENT_ID = STUDENT.STUDENT_ID
JOIN COURSE_SCHEDULE ON ENROLLMENT.SCHEDULE_ID = COURSE_SCHEDULE.SCHEDULE_ID AND ENROLLMENT.COURSE_NUM = COURSE_SCHEDULE.COURSE_NUM
JOIN COURSE ON COURSE_SCHEDULE.COURSE_NUM = COURSE.COURSE_NUM
WHERE
    ENROLLMENT.GRADE_ID = ASSIGNMENT.GRADE_ID AND
    ASSIGNMENT.ASSIGNMENT_NAME = 'List Basics' AND
    COURSE.COURSE_NAME = 'Introduction to Computer Science' AND
    COURSE_SCHEDULE.SEMESTER = 'Fall 2024';
