-- Test: Add 2 points to scores of students with 'Q' in their last name
UPDATE ASSIGNMENT
SET GRADE = GRADE + 2
WHERE GRADE_ID IN (SELECT GRADE_ID FROM ENROLLMENT WHERE STUDENT_ID IN (SELECT STUDENT_ID FROM STUDENT WHERE L_NAME LIKE '%Q%'));
-- Verify the update
SELECT * FROM ASSIGNMENT WHERE GRADE_ID IN (SELECT GRADE_ID FROM ENROLLMENT WHERE STUDENT_ID IN (SELECT STUDENT_ID FROM STUDENT WHERE L_NAME LIKE '%Q%'));
