UPDATE GRADE_DISTRIBUTION
SET HW_PERCENTAGE = 30, PROJECT_PERCENTAGE = 30, PARTICIPATION_PERCENTAGE = 20, TESTS_PERCENTAGE = 20
WHERE COURSE_NUM = 102 AND SCHEDULE_ID = 2;
-- Verify the change
SELECT * FROM GRADE_DISTRIBUTION WHERE COURSE_NUM = 102 AND SCHEDULE_ID = 2;
