-- Test: Compute grade for student ID 202, dropping the lowest homework score
WITH Homework_Scores AS (
    SELECT GRADE, ROW_NUMBER() OVER (ORDER BY GRADE ASC) AS rn
    FROM ASSIGNMENT
    WHERE ASSIGNMENT_ID IN (SELECT ASSIGNMENT_ID FROM ENROLLMENT WHERE STUDENT_ID = 202)
      AND ASSIGNMENT_NAME LIKE '%Homework%'
)
SELECT SUM(GRADE) AS Adjusted_Grade
FROM ASSIGNMENT
WHERE ASSIGNMENT_ID IN (SELECT ASSIGNMENT_ID FROM ENROLLMENT WHERE STUDENT_ID = 202)
  AND ASSIGNMENT_ID NOT IN (SELECT ASSIGNMENT_ID FROM Homework_Scores WHERE rn = 1);
